-- OutLawed India Seeding Data
-- Execute this script inside MySQL Workbench to populate the tables

USE outlawed_db;

-- 1. Seed Demo Users
INSERT INTO users (id, name, username, password, role) VALUES 
(1, 'Ananya Rao', 'mitra', 'password', 'mitra'),
(2, 'Suresh Kumar', 'coordinator', 'password', 'coordinator'),
(3, 'Dr. Priya Sharma', 'expert', 'password', 'expert')
ON DUPLICATE KEY UPDATE name=VALUES(name), role=VALUES(role);

-- 2. Seed Initial Case Records (explicit IDs matching React frontend)
INSERT INTO case_records (id, title, issue_type, district, location, urgency, status, language, follow_up_date, client_name, client_age, client_phone, file_name, situation, expert_question, expert_advisor, expert_comments, expert_answer_date, created_by, last_updated) VALUES
(1056, 'Land Partition Registry Dispute', 'Land / Property', 'Mandya', 'K R Pet Taluk', 'Important', 'Active', 'Kannada', '2026-09-10', 'Gowramma K.', 52, '+91 94480 12345', 'land_deed_2025.pdf', 'Family members have generated a false notarized partition sheet to deny inheritance rights of ancestral agricultural land. The partition document value exceeds Rs 100 but was never registered.', 'Are notarized division deeds valid for property partition exceeding Rs 100 without sub-registrar registration?', 'Dr. Priya Sharma', NULL, NULL, 'Ananya Rao', '2026-08-29'),
(1042, 'Domestic Violence Support Request', 'Domestic Violence', 'Mysuru', 'Hunsur Taluk', 'Urgent', 'Under Expert Review', 'Kannada', '2026-08-30', 'Lakshmi S.', 29, '+91 98450 67890', NULL, 'Physical abuse by spouse and in-laws demanding dowry. Client requires emergency protective shelter housing and guidance under domestic violence acts.', 'What immediate legal safety protection orders can be secured from magistrates before formal hearings?', 'Dr. Priya Sharma', NULL, NULL, 'Meena Kumar', '2026-08-29'),
(1038, 'Minimum Wage Claim', 'Employment', 'Tumakuru', 'Kunigal Taluk', 'Normal', 'Resolved', 'Kannada', '2026-08-25', 'Raju M.', 42, '+91 94800 54321', NULL, 'Sub-contractor has withheld three months of wages for building work completed.', NULL, 'Dr. Priya Sharma', 'Client was guided to file a petition before the local labor officer under Minimum Wages Act. The contractor agreed to pay the dues during joint consultation.', '2026-08-27', 'Kiran Das', '2026-08-28'),
(1071, 'Old Age Pension Application Delay', 'Government Scheme', 'Bengaluru', 'Yelahanka Hobli', 'Normal', 'Active', 'English', '2026-09-05', 'Ramegowda B.', 72, '+91 99000 88888', NULL, 'Senior citizen application for state pension scheme has been pending for over 8 months despite submitting all documents.', NULL, NULL, NULL, NULL, 'Ananya Rao', '2026-08-29')
ON DUPLICATE KEY UPDATE status=VALUES(status), situation=VALUES(situation);

-- 3. Seed Case Tasks Checklist
INSERT INTO case_tasks (id, case_id, title, due_date, done) VALUES
(1, 1056, 'Collect copy of RTC and mutation register from village accountant', '2026-09-02', FALSE),
(2, 1056, 'Verify death certificate of Gowramma''s father', '2026-09-05', TRUE),
(3, 1056, 'Draft caveat petition under Sec 148A CPC', '2026-09-09', FALSE),
(4, 1042, 'Arrange temporary shelter at district center', '2026-08-29', TRUE),
(5, 1042, 'Schedule consultation with Protection Officer', '2026-08-30', FALSE),
(6, 1038, 'File complaint at labor department office', '2026-08-24', TRUE),
(7, 1038, 'Retrieve signed daily labor attendance sheet', '2026-08-25', TRUE)
ON DUPLICATE KEY UPDATE done=VALUES(done);

-- 4. Seed Case Notes
INSERT INTO case_notes (id, case_id, text, author, created_at) VALUES
(1, 1056, 'Client reports that cousins threatened eviction yesterday. Urgency escalated.', 'Ananya Rao', '2026-08-29'),
(2, 1056, 'Checked similarity base; Case PC-001 appears highly relevant regarding documentation.', 'Ananya Rao', '2026-08-29'),
(3, 1042, 'Coordinated with district shelter home. Accommodation secured for 2 weeks.', 'Meena Kumar', '2026-08-29')
ON DUPLICATE KEY UPDATE text=VALUES(text);

-- 5. Seed 50 Anonymized Previously Resolved Cases
INSERT INTO previous_cases (id, title, issue_type, district, state, language, year, priority, problem, actions_taken, knowledge_used, outcome, resolution_summary, documents, tags, lessons_learned) VALUES
('PC-001', 'Agricultural Land Inheritance Dispute', 'Land / Property', 'Mandya', 'Karnataka', 'Kannada', 2025, 'Important', 'Family members disagreed about inheritance of agricultural land after the death of a family member.', 'Collected property documents,Verified family relationship records,Reviewed previous organizational cases,Consulted Human Legal Expert', 'Land inheritance documentation guidelines, Section 148A caveats.', 'Resolved', 'Required documentation was collected and the family was guided through the applicable partition processes.', 'Property record,Family relationship document', 'inheritance,land,property,documentation', 'Early collection of property and relationship documents helped reduce delays.'),
('PC-002', 'Property Boundary Dispute', 'Land / Property', 'Mysuru', 'Karnataka', 'Kannada', 2025, 'Normal', 'Two neighboring families had a disagreement regarding the recorded boundary of agricultural property.', 'Collected available property records,Reviewed organizational knowledge,Referred the case for human guidance', 'Previous property boundary cases, local taluk survey records guidelines.', 'Resolved', 'Relevant documentation was reviewed and the parties were guided toward the appropriate boundary resolution process.', 'Property record,Boundary document', 'property,boundary,agriculture', 'Clear documentation should be collected before escalating a property boundary dispute.'),
('PC-003', 'Government Scheme Documentation Support', 'Government Scheme', 'Tumakuru', 'Karnataka', 'Kannada', 2025, 'Normal', 'A community member was unsure about the documentation required for a welfare scheme application.', 'Searched organizational knowledge,Reviewed previous similar cases,Explained available documentation requirements', 'Welfare schemes checklist and family income certificate guidelines.', 'Resolved', 'The required documentation was identified and the person was able to proceed with the application process.', 'Identity document,Scheme application checklist', 'government,scheme,documentation', 'A simple documentation checklist can resolve many information-related requests.'),
('PC-004', 'Employment Documentation Issue', 'Employment', 'Bengaluru', 'Karnataka', 'English', 2025, 'Important', 'A worker needed assistance understanding employment documentation and payment terms.', 'Collected employment records,Searched previous organizational cases,Requested human expert guidance', 'Employment agreement terms and contract labor guidelines.', 'Resolved', 'The relevant documentation was organized and the worker was guided toward the appropriate support process.', 'Employment document,Communication record', 'employment,documents,worker', 'Organizing employment records early makes follow-up easier.'),
('PC-005', 'Family Documentation Support', 'Family', 'Kolar', 'Karnataka', 'Kannada', 2025, 'Normal', 'A family needed help organizing documents for a family related administrative process.', 'Reviewed documentation,Searched previous cases,Provided organizational guidance', 'Family records organization guidelines.', 'Resolved', 'Required documents were identified and organized for submission.', 'Family relationship document', 'family,documentation', 'Document organization can resolve many initial case barriers.'),
('PC-006', 'Domestic Violence Support Referral', 'Domestic Violence', 'Mysuru', 'Karnataka', 'Kannada', 2025, 'Urgent', 'A person requested support and information regarding available assistance and local shelters.', 'Recorded the case,Provided immediate organizational resources,Referred the case for Human Legal Expert guidance,Followed up with the person', 'Protection Officer contacts under domestic violence act protocols.', 'Support Completed', 'The person was connected with appropriate support resources through the organizational process.', 'Support resource list', 'domestic-violence,support,urgent', 'Urgent cases require quick identification and coordinated support.'),
('PC-007', 'Welfare Application Assistance', 'Government Scheme', 'Hassan', 'Karnataka', 'Kannada', 2025, 'Normal', 'Difficulty understanding a welfare application process and required eligibility files.', 'Knowledge search,Documentation review,Follow-up', 'Welfare scheme guidelines and registration procedures.', 'Resolved', 'Helped the applicant understand the documentation criteria and proceed with the application.', 'Scheme checklist', 'welfare,application', 'Maintaining a checklist for local schemes simplifies client onboarding.'),
('PC-008', 'Property Documentation Verification', 'Land / Property', 'Chikkamagaluru', 'Karnataka', 'Kannada', 2025, 'Normal', 'Missing property documentation created uncertainty about land partition boundaries.', 'Reviewed available records,Identified missing documentation,Followed organizational process', 'Revenue records tracking guidelines.', 'Resolved', 'Identified missing land titles and guided client on retrieving secondary copies from the sub-registrar.', 'Property record,Boundary document', 'property,documents', 'Cross-checking with the sub-registrar office solves missing record cases.'),
('PC-009', 'Employment Payment Documentation', 'Employment', 'Bengaluru', 'Karnataka', 'English', 2025, 'Important', 'Worker needed assistance organizing employment-related payment records.', 'Collected records,Reviewed similar organizational cases,Human expert guidance', 'Wage registry dispute guidelines.', 'Resolved', 'Payment slips and logs were compiled and verified for the client.', 'Employment document,Payment slip logs', 'employment,worker,records', 'Keep a structured timeline of work hours for employment complaints.'),
('PC-010', 'Family Property Documentation', 'Family', 'Mandya', 'Karnataka', 'Kannada', 2025, 'Normal', 'Family needed help organizing property-related records and partition documents.', 'Document collection,Knowledge search,Follow-up', 'Partition deed registration requirements.', 'Resolved', 'Assisted in categorizing family partition deeds and ancestral registration proofs.', 'Property record', 'family,property', 'Verify deed registration status before drafting family partition agreements.'),
('PC-011', 'Identity Documentation Support', 'Documentation', 'Tumakuru', 'Karnataka', 'Kannada', 2024, 'Normal', 'Difficulty identifying required identity documents for general legal-aid intake.', 'Knowledge search,Documentation checklist review', 'Identity record verification protocols.', 'Documentation Completed', 'Identified the list of credentials required to update name details.', 'Identity document', 'identity,documents', 'Standard identity guides reduce customer waiting times.'),
('PC-012', 'Agricultural Lease Documentation', 'Land / Property', 'Hassan', 'Karnataka', 'Kannada', 2024, 'Important', 'Uncertainty around agricultural lease records and tenancy duration agreements.', 'Document review,Human expert guidance', 'Karnataka agricultural lease and tenancy guidelines.', 'Resolved', 'Reviewed the lease parameters and guided the tenant on tenancy preservation options.', 'Lease document', 'land,lease', 'Written lease agreements are essential to protect agricultural tenant rights.'),
('PC-013', 'Workplace Documentation Support', 'Employment', 'Mysuru', 'Karnataka', 'Kannada', 2024, 'Normal', 'Worker needed help organizing workplace documents and appointment letters.', 'Document organization guidance', 'Workplace appointment letters checklist.', 'Resolved', 'Helped the employee organize appointment letters and salary slips.', 'Employment document', 'employment,documentation', 'Store digital backups of all employment-related paperwork.'),
('PC-014', 'Family Support Documentation', 'Family', 'Kolar', 'Karnataka', 'Kannada', 2024, 'Normal', 'Required documents for family welfare claims were unclear.', 'Checked document checklist', 'Family welfare support document templates.', 'Documentation Completed', 'Helped compile relationship documents to file for family benefits.', 'Family relationship document', 'family,documents', 'Prepare relationship documents in advance of filing requests.'),
('PC-015', 'Government Benefit Application', 'Government Scheme', 'Mandya', 'Karnataka', 'Kannada', 2024, 'Important', 'Applicant needed support understanding available scheme documentation and eligibility rules.', 'Reviewed eligibility parameters,Knowledge database check', 'State welfare scheme registration rules.', 'Resolved', 'Helped the client register online for regional agricultural subsidies.', 'Identity document,Scheme checklist', 'government,benefit', 'Online registry guides are highly effective for rural subsidies.'),
('PC-016', 'Land Record Update Support', 'Land / Property', 'Tumakuru', 'Karnataka', 'Kannada', 2024, 'Normal', 'Property record RTC name required correction at the local taluk office.', 'Drafted correction request,Verified land titles', 'Karnataka Land Revenue RTC correction guidelines.', 'Resolved', 'The name correction request was reviewed and submitted to the local Tehsildar office.', 'Property record', 'land,records', 'Cross-reference RTC names with identity files before applying.'),
('PC-017', 'Domestic Violence Resource Referral', 'Domestic Violence', 'Bengaluru', 'Karnataka', 'English', 2024, 'Urgent', 'Person required information about emergency shelter resources.', 'Provided emergency contact list,Assisted in contacting shelter support', 'Emergency shelter access guidelines.', 'Support Completed', 'The client was safely referred to shelter housing and counselor assistance.', 'Support resource list', 'domestic-violence,referral', 'Immediate placement references are vital for urgent safety needs.'),
('PC-018', 'Employment Record Assistance', 'Employment', 'Kolar', 'Karnataka', 'Kannada', 2024, 'Normal', 'Employment records and experience letters were incomplete.', 'Compiled salary slips,Consulted legal-aid database', 'Experience letter verification guidelines.', 'Resolved', 'Helped the client draft a letter to the HR department to retrieve credentials.', 'Employment document', 'employment,records', 'Retain physical copies of resignation acceptances.'),
('PC-019', 'Property Inheritance Documentation', 'Land / Property', 'Mysuru', 'Karnataka', 'Kannada', 2024, 'Important', 'Family needed help organizing inheritance documents for partition claims.', 'Collected ancestral land files,Knowledge search', 'Land partition registration requirements.', 'Resolved', 'Compiled the family tree and property deeds to prepare for amicable settlement.', 'Property record,Family relationship document', 'inheritance,property', 'Amicable settlements are faster than litigation in civil courts.'),
('PC-020', 'Welfare Scheme Eligibility Information', 'Government Scheme', 'Hassan', 'Karnataka', 'Kannada', 2024, 'Normal', 'Person needed help understanding available organizational information about a welfare scheme.', 'Explained eligibility checklist,Shared application guidelines', 'Government scheme rules checklist.', 'Resolved', 'Verified client income status and confirmed eligibility for scheme filing.', 'Identity document', 'scheme,welfare', 'Income verification prevents early application rejections.'),
('PC-021', 'Agricultural Property Record Issue', 'Land / Property', 'Mandya', 'Karnataka', 'Kannada', 2023, 'Important', 'Agricultural property records needed clarification on boundaries and names.', 'Reviewed RTC details,Cross-checked with taluk map', 'Agricultural land records validation.', 'Resolved', 'Helped resolve the name differences in the registry files.', 'Property record', 'agriculture,property', 'Taluk maps provide final authority on boundary claims.'),
('PC-022', 'Workplace Documentation Request', 'Employment', 'Bengaluru', 'Karnataka', 'English', 2023, 'Normal', 'Worker needed assistance understanding workplace records and overtime pay.', 'Reviewed pay registers,Prepared documentation file', 'Overtime payment guidelines.', 'Resolved', 'Organized overtime logs to present to the local grievance officer.', 'Employment document', 'employment', 'Log overtime hours on calendar cards as secondary proof.'),
('PC-023', 'Family Documentation Request', 'Family', 'Tumakuru', 'Karnataka', 'Kannada', 2023, 'Normal', 'Family needed help identifying documents for birth certificate correction.', 'Verified correction checklist', 'Birth certificate correction procedures.', 'Documentation Completed', 'Helped compile school certificates to support name corrections.', 'Identity document', 'family', 'School records are reliable backups for birth certificates.'),
('PC-024', 'Domestic Support Resource Case', 'Domestic Violence', 'Mysuru', 'Karnataka', 'Kannada', 2023, 'Urgent', 'Person requested information about available support and protection programs.', 'Provided shelter directory,Contacted NGO counselors', 'Protection guidelines for domestic disputes.', 'Support Completed', 'Connected the client with legal-aid NGO counseling services.', 'Support resource list', 'support,domestic-violence', 'NGO linkages improve support coverage.'),
('PC-025', 'Land Documentation Assistance', 'Land / Property', 'Kolar', 'Karnataka', 'Kannada', 2023, 'Normal', 'Property documentation was incomplete due to missing sale deeds.', 'Applied for certified copy,Searched local records', 'Retrieval of certified deed copies.', 'Resolved', 'Obtained a certified copy of the sale deed from the sub-registrar office.', 'Property record', 'land,documentation', 'Sub-registrar indexes retain copies of all registered sales.'),
('PC-026', 'Government Documentation Help', 'Government Scheme', 'Mandya', 'Karnataka', 'Kannada', 2023, 'Normal', 'Application documentation for rural house building subsidy was unclear.', 'Explained house scheme forms,Checked document completeness', 'Rural housing eligibility rules.', 'Resolved', 'Assisted in completing the application file for the local panchayat office.', 'Scheme checklist', 'government,documents', 'Panchayat approvals are easier to obtain when files are complete.'),
('PC-027', 'Employment Record Dispute', 'Employment', 'Mysuru', 'Karnataka', 'Kannada', 2023, 'Important', 'Worker required assistance organizing records for termination claims.', 'Collected termination notice,Reviewed guidelines', 'Termination notices checklists.', 'Resolved', 'Helped draft a response requesting clarification on pending payments.', 'Employment document', 'employment', 'Request written termination reasons immediately.'),
('PC-028', 'Property Ownership Documentation', 'Land / Property', 'Hassan', 'Karnataka', 'Kannada', 2023, 'Important', 'Ownership documentation required review for ancestral property partition.', 'Reviewed title deeds,Verified inheritance sequence', 'Ancestral property inheritance laws.', 'Resolved', 'Amicably guided the heirs on dividing the land parcels.', 'Property record', 'property,ownership', 'Establish ownership chains before partition agreements.'),
('PC-029', 'Family Support Case', 'Family', 'Bengaluru', 'Karnataka', 'English', 2023, 'Normal', 'Family needed organizational support for updating senior citizen cards.', 'Checked senior scheme criteria,Verified identity proofs', 'Senior citizen registration rules.', 'Resolved', 'Coordinated online registration for the client card.', 'Identity document', 'family', 'Senior card registration simplifies medical welfare access.'),
('PC-030', 'Documentation Recovery Support', 'Documentation', 'Tumakuru', 'Karnataka', 'Kannada', 2023, 'Important', 'Important ration card documents were unavailable due to flood damage.', 'Assisted in filing damage report,Applied for duplicate ration card', 'Duplicate ration card guidelines.', 'Documentation Completed', 'Helped the client obtain a duplicate copy of their food security card.', 'Identity document', 'documents,recovery', 'Keep digital photocopies of welfare cards online.'),
('PC-031', 'Agricultural Land Record Case', 'Land / Property', 'Mandya', 'Karnataka', 'Kannada', 2022, 'Normal', 'Land records and RTC entries required clarification for agricultural credit.', 'Reviewed RTC details,Assisted in credit guidelines review', 'Agricultural credit documentation rules.', 'Resolved', 'Helped clarify name records to clear bank loan conditions.', 'Property record', 'land,agriculture', 'Ensure RTC name matches bank records before applying for loans.'),
('PC-032', 'Employment Documentation Case', 'Employment', 'Bengaluru', 'Karnataka', 'English', 2022, 'Normal', 'Worker required documentation assistance for employee provident fund (PF) queries.', 'Checked PF portal details,Verified UAN activation steps', 'PF registry procedures.', 'Resolved', 'Assisted the client in logging into the portal and updating their profile.', 'Employment document', 'employment', 'UAN updates require matching Aadhaar details.'),
('PC-033', 'Domestic Violence Support Case', 'Domestic Violence', 'Kolar', 'Karnataka', 'Kannada', 2022, 'Urgent', 'Person required coordinated safety support and legal awareness advice.', 'Coordinated counseling sessions,Helped write incident logs', 'Domestic violence support guidelines.', 'Support Completed', 'Assisted in filing safety incidents logs and provided protective shelter.', 'Support resource list', 'domestic-violence', 'Detailed incident diaries act as strong evidence during reviews.'),
('PC-034', 'Government Scheme Documentation', 'Government Scheme', 'Mysuru', 'Karnataka', 'Kannada', 2022, 'Normal', 'Applicant needed documentation support for the maternal benefit scheme.', 'Verified medical checkup cards,Checked bank account link status', 'Maternal scheme registration checklist.', 'Resolved', 'Helped client update bank details to receive maternal benefit transfers.', 'Identity document,Scheme checklist', 'scheme,documents', 'Ensure the bank account is Aadhaar seeded for government scheme payments.'),
('PC-035', 'Property Documentation Case', 'Land / Property', 'Tumakuru', 'Karnataka', 'Kannada', 2022, 'Important', 'Property documents needed review for partition of family homestead.', 'Compiled ancient partition records,Consulted senior expert', 'Homestead partition guidelines.', 'Resolved', 'Helped siblings divide properties through registered mutual agreements.', 'Property record', 'property', 'Registered mutual agreements prevent future boundary disputes.'),
('PC-036', 'Family Record Support', 'Family', 'Hassan', 'Karnataka', 'Kannada', 2022, 'Normal', 'Family records and child immunization data required organization for school admissions.', 'Compiled health cards,Drafted admission files', 'School admission documentation guides.', 'Resolved', 'Organized childhood health logs to secure local primary school admission.', 'Identity document', 'family,records', 'Keep immunizations cards updated for primary registrations.'),
('PC-037', 'Employment Support Case', 'Employment', 'Mandya', 'Karnataka', 'Kannada', 2022, 'Important', 'Worker required support understanding employment records after injury.', 'Collected medical reports,Reviewed compensation procedures', 'Workplace injury compensation guidelines.', 'Resolved', 'Helped compile medical cards and injury reports for filing.', 'Employment document,Medical records', 'employment', 'Log injury details within 24 hours of incident.'),
('PC-038', 'Land Inheritance Documentation', 'Land / Property', 'Mysuru', 'Karnataka', 'Kannada', 2022, 'Important', 'Inheritance records required organization for agricultural property partition.', 'Collected death certificates,Verified legal heir certificates', 'Legal heir certification rules.', 'Resolved', 'Helped client obtain legal heir documents to register properties.', 'Property record,Family relationship document', 'inheritance,land', 'Obtain death certificates within 30 days of demise.'),
('PC-039', 'Government Benefit Documentation', 'Government Scheme', 'Kolar', 'Karnataka', 'Kannada', 2022, 'Normal', 'Required documentation for disability pension benefit was unclear.', 'Verified medical certificate rules,Checked application form', 'Disability pension scheme rules.', 'Documentation Completed', 'Compiled medical certificates and applied for disability pension.', 'Identity document,Scheme checklist', 'government,benefit', 'Medical certificates must be signed by authorized doctors.'),
('PC-040', 'Domestic Support Referral', 'Domestic Violence', 'Bengaluru', 'Karnataka', 'English', 2022, 'Urgent', 'Person needed access to support resources and legal counseling options.', 'Referred to local protection desk,Provided resource list', 'Protection officer liaison procedures.', 'Support Completed', 'Client was linked with family counseling support.', 'Support resource list', 'domestic-violence,support', 'Early counseling prevents escalation of family disputes.'),
('PC-041', 'Property Boundary Documentation', 'Land / Property', 'Hassan', 'Karnataka', 'Kannada', 2021, 'Important', 'Property boundary documentation required review for building partition fence.', 'Reviewed boundary survey map,Spoke to neighbors', 'Land survey map validation.', 'Resolved', 'Boundary coordinates were verified to build fence.', 'Property record,Boundary document', 'property,boundary', 'Review survey maps before constructing boundary fences.'),
('PC-042', 'Employment Record Support', 'Employment', 'Tumakuru', 'Karnataka', 'Kannada', 2021, 'Normal', 'Employment records and contract copies required organization for pending claims.', 'Organized employment logs,Reviewed contract rules', 'Contract laborer protection rules.', 'Resolved', 'Helped employee organize work logs to settle contract claims.', 'Employment document', 'employment,records', 'Retain copies of signed work contracts.'),
('PC-043', 'Family Documentation Case', 'Family', 'Mandya', 'Karnataka', 'Kannada', 2021, 'Normal', 'Family documentation for marriage registration certificate was incomplete.', 'Checked marriage certificate rules,Verified age proofs', 'Marriage registration guidelines.', 'Documentation Completed', 'Assisted in obtaining the marriage registration certificate.', 'Family relationship document', 'family,documents', 'Collect birth certificates of both spouses for registrations.'),
('PC-044', 'Welfare Scheme Support', 'Government Scheme', 'Mysuru', 'Karnataka', 'Kannada', 2021, 'Normal', 'Applicant needed help understanding documentation for housing scheme.', 'Explained income certificate rules,Verified caste certificate details', 'Housing scheme documentation guides.', 'Resolved', 'Helped compile caste and income certificates for housing scheme.', 'Identity document,Scheme checklist', 'scheme,welfare', 'Renew caste and income certificates annually.'),
('PC-045', 'Land Record Support', 'Land / Property', 'Kolar', 'Karnataka', 'Kannada', 2021, 'Important', 'Land records and mutation entry RTC documents required clarification.', 'Checked mutation registry entries,Verified property titles', 'Property mutation guidelines.', 'Resolved', 'Assisted client in tracking mutation status at local sub-office.', 'Property record', 'land,records', 'Verify mutation status within 90 days of registration.'),
('PC-046', 'Documentation Assistance Case', 'Documentation', 'Bengaluru', 'Karnataka', 'English', 2021, 'Normal', 'Person needed help organizing official documents for credit applications.', 'Compiled salary statements,Verified address proofs', 'Address proof validation checklist.', 'Documentation Completed', 'Organized utility bills and identity proofs to update bank records.', 'Identity document', 'documentation', 'Utility bills must be under 3 months old to count as address proof.'),
('PC-047', 'Employment Documentation Review', 'Employment', 'Mandya', 'Karnataka', 'Kannada', 2021, 'Important', 'Employment records and contract copies required review after salary delay.', 'Checked work contracts,Drafted request letter', 'Wage payment dispute procedures.', 'Resolved', 'Assisted in filing a request to clarify outstanding wage payments.', 'Employment document', 'employment', 'Avoid working without a signed copy of the employment contract.'),
('PC-048', 'Family Property Support', 'Family', 'Tumakuru', 'Karnataka', 'Kannada', 2021, 'Normal', 'Family required assistance organizing property records and tax receipts.', 'Collected tax challan records,Reviewed payment entries', 'Family property tax tracking.', 'Resolved', 'Compiled and organized 5 years of family property tax receipts.', 'Property record', 'family,property', 'Keep property tax receipts in chronological order.'),
('PC-049', 'Domestic Violence Support Referral', 'Domestic Violence', 'Hassan', 'Karnataka', 'Kannada', 2021, 'Urgent', 'Person required safety counseling support and legal protection links.', 'Liaised with protection desk,Shared resources folder', 'Counseling referral procedures.', 'Support Completed', 'Helped link the client with district protection counselor.', 'Support resource list', 'domestic-violence,referral', 'Direct linkages improve counselor outreach success.'),
('PC-050', 'Government Documentation Support', 'Government Scheme', 'Kolar', 'Karnataka', 'Kannada', 2021, 'Normal', 'Applicant required help identifying supporting documents for housing subsidy.', 'Verified local property deeds,Knowledge checklist search', 'Housing subsidy eligibility guides.', 'Resolved', 'Helped compile local property deeds to complete the housing application.', 'Identity document,Scheme checklist', 'government,documentation', 'Ensure deeds are clearly readable before uploading.')
ON DUPLICATE KEY UPDATE title=VALUES(title), problem=VALUES(problem);
