/**
 * Centralized Mock Database of 50 Anonymized, Previously Resolved/Solved Cases
 * Used as the core organizational knowledge repository.
 */
export const mockPreviousCases = [
  {
    id: 'PC-001',
    title: 'Agricultural Land Inheritance Dispute',
    issueType: 'Land / Property',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Important',
    problem: 'Family members disagreed about inheritance of agricultural land after the death of a family member.',
    actionsTaken: [
      'Collected property documents',
      'Verified family relationship records',
      'Reviewed previous organizational cases',
      'Consulted Human Legal Expert'
    ],
    knowledgeUsed: 'Land inheritance documentation guidelines, Section 148A caveats.',
    outcome: 'Resolved',
    resolutionSummary: 'Required documentation was collected and the family was guided through the applicable partition processes.',
    documents: ['Property record', 'Family relationship document'],
    lessonsLearned: 'Early collection of property and relationship documents helped reduce delays.',
    tags: ['inheritance', 'land', 'property', 'documentation']
  },
  {
    id: 'PC-002',
    title: 'Property Boundary Dispute',
    issueType: 'Land / Property',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'Two neighboring families had a disagreement regarding the recorded boundary of agricultural property.',
    actionsTaken: [
      'Collected available property records',
      'Reviewed organizational knowledge',
      'Referred the case for human guidance'
    ],
    knowledgeUsed: 'Previous property boundary cases, local taluk survey records guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Relevant documentation was reviewed and the parties were guided toward the appropriate boundary resolution process.',
    documents: ['Property record', 'Boundary document'],
    lessonsLearned: 'Clear documentation should be collected before escalating a property boundary dispute.',
    tags: ['property', 'boundary', 'agriculture']
  },
  {
    id: 'PC-003',
    title: 'Government Scheme Documentation Support',
    issueType: 'Government Scheme',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'A community member was unsure about the documentation required for a welfare scheme application.',
    actionsTaken: [
      'Searched organizational knowledge',
      'Reviewed previous similar cases',
      'Explained available documentation requirements'
    ],
    knowledgeUsed: 'Welfare schemes checklist and family income certificate guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'The required documentation was identified and the person was able to proceed with the application process.',
    documents: ['Identity document', 'Scheme application checklist'],
    lessonsLearned: 'A simple documentation checklist can resolve many information-related requests.',
    tags: ['government', 'scheme', 'documentation']
  },
  {
    id: 'PC-004',
    title: 'Employment Documentation Issue',
    issueType: 'Employment',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2025,
    priority: 'Important',
    problem: 'A worker needed assistance understanding employment documentation and payment terms.',
    actionsTaken: [
      'Collected employment records',
      'Searched previous organizational cases',
      'Requested human expert guidance'
    ],
    knowledgeUsed: 'Employment agreement terms and contract labor guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'The relevant documentation was organized and the worker was guided toward the appropriate support process.',
    documents: ['Employment document', 'Communication record'],
    lessonsLearned: 'Organizing employment records early makes follow-up easier.',
    tags: ['employment', 'documents', 'worker']
  },
  {
    id: 'PC-005',
    title: 'Family Documentation Support',
    issueType: 'Family',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'A family needed help organizing documents for a family related administrative process.',
    actionsTaken: [
      'Reviewed documentation',
      'Searched previous cases',
      'Provided organizational guidance'
    ],
    knowledgeUsed: 'Family records organization guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Required documents were identified and organized for submission.',
    documents: ['Family relationship document'],
    lessonsLearned: 'Document organization can resolve many initial case barriers.',
    tags: ['family', 'documentation']
  },
  {
    id: 'PC-006',
    title: 'Domestic Violence Support Referral',
    issueType: 'Domestic Violence',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Urgent',
    problem: 'A person requested support and information regarding available assistance and local shelters.',
    actionsTaken: [
      'Recorded the case',
      'Provided immediate organizational resources',
      'Referred the case for Human Legal Expert guidance',
      'Followed up with the person'
    ],
    knowledgeUsed: 'Protection Officer contacts under domestic violence act protocols.',
    outcome: 'Support Completed',
    resolutionSummary: 'The person was connected with appropriate support resources through the organizational process.',
    documents: ['Support resource list'],
    lessonsLearned: 'Urgent cases require quick identification and coordinated support.',
    tags: ['domestic-violence', 'support', 'urgent']
  },
  {
    id: 'PC-007',
    title: 'Welfare Application Assistance',
    issueType: 'Government Scheme',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'Difficulty understanding a welfare application process and required eligibility files.',
    actionsTaken: [
      'Knowledge search',
      'Documentation review',
      'Follow-up'
    ],
    knowledgeUsed: 'Welfare scheme guidelines and registration procedures.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped the applicant understand the documentation criteria and proceed with the application.',
    documents: ['Scheme checklist'],
    lessonsLearned: 'Maintaining a checklist for local schemes simplifies client onboarding.',
    tags: ['welfare', 'application']
  },
  {
    id: 'PC-008',
    title: 'Property Documentation Verification',
    issueType: 'Land / Property',
    district: 'Chikkamagaluru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'Missing property documentation created uncertainty about land partition boundaries.',
    actionsTaken: [
      'Reviewed available records',
      'Identified missing documentation',
      'Followed organizational process'
    ],
    knowledgeUsed: 'Revenue records tracking guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Identified missing land titles and guided client on retrieving secondary copies from the sub-registrar.',
    documents: ['Property record', 'Boundary document'],
    lessonsLearned: 'Cross-checking with the sub-registrar office solves missing record cases.',
    tags: ['property', 'documents']
  },
  {
    id: 'PC-009',
    title: 'Employment Payment Documentation',
    issueType: 'Employment',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2025,
    priority: 'Important',
    problem: 'Worker needed assistance organizing employment-related payment records.',
    actionsTaken: [
      'Collected records',
      'Reviewed similar organizational cases',
      'Human expert guidance'
    ],
    knowledgeUsed: 'Wage registry dispute guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Payment slips and logs were compiled and verified for the client.',
    documents: ['Employment document', 'Payment slip logs'],
    lessonsLearned: 'Keep a structured timeline of work hours for employment complaints.',
    tags: ['employment', 'worker', 'records']
  },
  {
    id: 'PC-010',
    title: 'Family Property Documentation',
    issueType: 'Family',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2025,
    priority: 'Normal',
    problem: 'Family needed help organizing property-related records and partition documents.',
    actionsTaken: [
      'Document collection',
      'Knowledge search',
      'Follow-up'
    ],
    knowledgeUsed: 'Partition deed registration requirements.',
    outcome: 'Resolved',
    resolutionSummary: 'Assisted in categorizing family partition deeds and ancestral registration proofs.',
    documents: ['Property record'],
    lessonsLearned: 'Verify deed registration status before drafting family partition agreements.',
    tags: ['family', 'property']
  },
  {
    id: 'PC-011',
    title: 'Identity Documentation Support',
    issueType: 'Documentation',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Difficulty identifying required identity documents for general legal-aid intake.',
    actionsTaken: [
      'Knowledge search',
      'Documentation checklist review'
    ],
    knowledgeUsed: 'Identity record verification protocols.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Identified the list of credentials required to update name details.',
    documents: ['Identity document'],
    lessonsLearned: 'Standard identity guides reduce customer waiting times.',
    tags: ['identity', 'documents']
  },
  {
    id: 'PC-012',
    title: 'Agricultural Lease Documentation',
    issueType: 'Land / Property',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Important',
    problem: 'Uncertainty around agricultural lease records and tenancy duration agreements.',
    actionsTaken: [
      'Document review',
      'Human expert guidance'
    ],
    knowledgeUsed: 'Karnataka agricultural lease and tenancy guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Reviewed the lease parameters and guided the tenant on tenancy preservation options.',
    documents: ['Lease document'],
    lessonsLearned: 'Written lease agreements are essential to protect agricultural tenant rights.',
    tags: ['land', 'lease']
  },
  {
    id: 'PC-013',
    title: 'Workplace Documentation Support',
    issueType: 'Employment',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Worker needed help organizing workplace documents and appointment letters.',
    actionsTaken: [
      'Document organization guidance'
    ],
    knowledgeUsed: 'Workplace appointment letters checklist.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped the employee organize appointment letters and salary slips.',
    documents: ['Employment document'],
    lessonsLearned: 'Store digital backups of all employment-related paperwork.',
    tags: ['employment', 'documentation']
  },
  {
    id: 'PC-014',
    title: 'Family Support Documentation',
    issueType: 'Family',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Required documents for family welfare claims were unclear.',
    actionsTaken: [
      'Checked document checklist'
    ],
    knowledgeUsed: 'Family welfare support document templates.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Helped compile relationship documents to file for family benefits.',
    documents: ['Family relationship document'],
    lessonsLearned: 'Prepare relationship documents in advance of filing requests.',
    tags: ['family', 'documents']
  },
  {
    id: 'PC-015',
    title: 'Government Benefit Application',
    issueType: 'Government Scheme',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Important',
    problem: 'Applicant needed support understanding available scheme documentation and eligibility rules.',
    actionsTaken: [
      'Reviewed eligibility parameters',
      'Knowledge database check'
    ],
    knowledgeUsed: 'State welfare scheme registration rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped the client register online for regional agricultural subsidies.',
    documents: ['Identity document', 'Scheme checklist'],
    lessonsLearned: 'Online registry guides are highly effective for rural subsidies.',
    tags: ['government', 'benefit']
  },
  {
    id: 'PC-016',
    title: 'Land Record Update Support',
    issueType: 'Land / Property',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Property record RTC name required correction at the local taluk office.',
    actionsTaken: [
      'Drafted correction request',
      'Verified land titles'
    ],
    knowledgeUsed: 'Karnataka Land Revenue RTC correction guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'The name correction request was reviewed and submitted to the local Tehsildar office.',
    documents: ['Property record'],
    lessonsLearned: 'Cross-reference RTC names with identity files before applying.',
    tags: ['land', 'records']
  },
  {
    id: 'PC-017',
    title: 'Domestic Violence Resource Referral',
    issueType: 'Domestic Violence',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2024,
    priority: 'Urgent',
    problem: 'Person required information about emergency shelter resources.',
    actionsTaken: [
      'Provided emergency contact list',
      'Assisted in contacting shelter support'
    ],
    knowledgeUsed: 'Emergency shelter access guidelines.',
    outcome: 'Support Completed',
    resolutionSummary: 'The client was safely referred to shelter housing and counselor assistance.',
    documents: ['Support resource list'],
    lessonsLearned: 'Immediate placement references are vital for urgent safety needs.',
    tags: ['domestic-violence', 'referral']
  },
  {
    id: 'PC-018',
    title: 'Employment Record Assistance',
    issueType: 'Employment',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Employment records and experience letters were incomplete.',
    actionsTaken: [
      'Compiled salary slips',
      'Consulted legal-aid database'
    ],
    knowledgeUsed: 'Experience letter verification guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped the client draft a letter to the HR department to retrieve credentials.',
    documents: ['Employment document'],
    lessonsLearned: 'Retain physical copies of resignation acceptances.',
    tags: ['employment', 'records']
  },
  {
    id: 'PC-019',
    title: 'Property Inheritance Documentation',
    issueType: 'Land / Property',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Important',
    problem: 'Family needed help organizing inheritance documents for partition claims.',
    actionsTaken: [
      'Collected ancestral land files',
      'Knowledge search'
    ],
    knowledgeUsed: 'Land partition registration requirements.',
    outcome: 'Resolved',
    resolutionSummary: 'Compiled the family tree and property deeds to prepare for amicable settlement.',
    documents: ['Property record', 'Family relationship document'],
    lessonsLearned: 'Amicable settlements are faster than litigation in civil courts.',
    tags: ['inheritance', 'property']
  },
  {
    id: 'PC-020',
    title: 'Welfare Scheme Eligibility Information',
    issueType: 'Government Scheme',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2024,
    priority: 'Normal',
    problem: 'Person needed help understanding available organizational information about a welfare scheme.',
    actionsTaken: [
      'Explained eligibility checklist',
      'Shared application guidelines'
    ],
    knowledgeUsed: 'Government scheme rules checklist.',
    outcome: 'Resolved',
    resolutionSummary: 'Verified client income status and confirmed eligibility for scheme filing.',
    documents: ['Identity document'],
    lessonsLearned: 'Income verification prevents early application rejections.',
    tags: ['scheme', 'welfare']
  },
  {
    id: 'PC-021',
    title: 'Agricultural Property Record Issue',
    issueType: 'Land / Property',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Important',
    problem: 'Agricultural property records needed clarification on boundaries and names.',
    actionsTaken: [
      'Reviewed RTC details',
      'Cross-checked with taluk map'
    ],
    knowledgeUsed: 'Agricultural land records validation.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped resolve the name differences in the registry files.',
    documents: ['Property record'],
    lessonsLearned: 'Taluk maps provide final authority on boundary claims.',
    tags: ['agriculture', 'property']
  },
  {
    id: 'PC-022',
    title: 'Workplace Documentation Request',
    issueType: 'Employment',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2023,
    priority: 'Normal',
    problem: 'Worker needed assistance understanding workplace records and overtime pay.',
    actionsTaken: [
      'Reviewed pay registers',
      'Prepared documentation file'
    ],
    knowledgeUsed: 'Overtime payment guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Organized overtime logs to present to the local grievance officer.',
    documents: ['Employment document'],
    lessonsLearned: 'Log overtime hours on calendar cards as secondary proof.',
    tags: ['employment']
  },
  {
    id: 'PC-023',
    title: 'Family Documentation Request',
    issueType: 'Family',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Normal',
    problem: 'Family needed help identifying documents for birth certificate correction.',
    actionsTaken: [
      'Verified correction checklist'
    ],
    knowledgeUsed: 'Birth certificate correction procedures.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Helped compile school certificates to support name corrections.',
    documents: ['Identity document'],
    lessonsLearned: 'School records are reliable backups for birth certificates.',
    tags: ['family']
  },
  {
    id: 'PC-024',
    title: 'Domestic Support Resource Case',
    issueType: 'Domestic Violence',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Urgent',
    problem: 'Person requested information about available support and protection programs.',
    actionsTaken: [
      'Provided shelter directory',
      'Contacted NGO counselors'
    ],
    knowledgeUsed: 'Protection guidelines for domestic disputes.',
    outcome: 'Support Completed',
    resolutionSummary: 'Connected the client with legal-aid NGO counseling services.',
    documents: ['Support resource list'],
    lessonsLearned: 'NGO linkages improve support coverage.',
    tags: ['support', 'domestic-violence']
  },
  {
    id: 'PC-025',
    title: 'Land Documentation Assistance',
    issueType: 'Land / Property',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Normal',
    problem: 'Property documentation was incomplete due to missing sale deeds.',
    actionsTaken: [
      'Applied for certified copy',
      'Searched local records'
    ],
    knowledgeUsed: 'Retrieval of certified deed copies.',
    outcome: 'Resolved',
    resolutionSummary: 'Obtained a certified copy of the sale deed from the sub-registrar office.',
    documents: ['Property record'],
    lessonsLearned: 'Sub-registrar indexes retain copies of all registered sales.',
    tags: ['land', 'documentation']
  },
  {
    id: 'PC-026',
    title: 'Government Documentation Help',
    issueType: 'Government Scheme',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Normal',
    problem: 'Application documentation for rural house building subsidy was unclear.',
    actionsTaken: [
      'Explained house scheme forms',
      'Checked document completeness'
    ],
    knowledgeUsed: 'Rural housing eligibility rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Assisted in completing the application file for the local panchayat office.',
    documents: ['Scheme checklist'],
    lessonsLearned: 'Panchayat approvals are easier to obtain when files are complete.',
    tags: ['government', 'documents']
  },
  {
    id: 'PC-027',
    title: 'Employment Record Dispute',
    issueType: 'Employment',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Important',
    problem: 'Worker required assistance organizing records for termination claims.',
    actionsTaken: [
      'Collected termination notice',
      'Reviewed guidelines'
    ],
    knowledgeUsed: 'Termination notices checklists.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped draft a response requesting clarification on pending payments.',
    documents: ['Employment document'],
    lessonsLearned: 'Request written termination reasons immediately.',
    tags: ['employment']
  },
  {
    id: 'PC-028',
    title: 'Property Ownership Documentation',
    issueType: 'Land / Property',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Important',
    problem: 'Ownership documentation required review for ancestral property partition.',
    actionsTaken: [
      'Reviewed title deeds',
      'Verified inheritance sequence'
    ],
    knowledgeUsed: 'Ancestral property inheritance laws.',
    outcome: 'Resolved',
    resolutionSummary: 'Amicably guided the heirs on dividing the land parcels.',
    documents: ['Property record'],
    lessonsLearned: 'Establish ownership chains before partition agreements.',
    tags: ['property', 'ownership']
  },
  {
    id: 'PC-029',
    title: 'Family Support Case',
    issueType: 'Family',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2023,
    priority: 'Normal',
    problem: 'Family needed organizational support for updating senior citizen cards.',
    actionsTaken: [
      'Checked senior scheme criteria',
      'Verified identity proofs'
    ],
    knowledgeUsed: 'Senior citizen registration rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Coordinated online registration for the client card.',
    documents: ['Identity document'],
    lessonsLearned: 'Senior card registration simplifies medical welfare access.',
    tags: ['family']
  },
  {
    id: 'PC-030',
    title: 'Documentation Recovery Support',
    issueType: 'Documentation',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2023,
    priority: 'Important',
    problem: 'Important ration card documents were unavailable due to flood damage.',
    actionsTaken: [
      'Assisted in filing damage report',
      'Applied for duplicate ration card'
    ],
    knowledgeUsed: 'Duplicate ration card guidelines.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Helped the client obtain a duplicate copy of their food security card.',
    documents: ['Identity document'],
    lessonsLearned: 'Keep digital photocopies of welfare cards online.',
    tags: ['documents', 'recovery']
  },
  {
    id: 'PC-031',
    title: 'Agricultural Land Record Case',
    issueType: 'Land / Property',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Normal',
    problem: 'Land records and RTC entries required clarification for agricultural credit.',
    actionsTaken: [
      'Reviewed RTC details',
      'Assisted in credit guidelines review'
    ],
    knowledgeUsed: 'Agricultural credit documentation rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped clarify name records to clear bank loan conditions.',
    documents: ['Property record'],
    lessonsLearned: 'Ensure RTC name matches bank records before applying for loans.',
    tags: ['land', 'agriculture']
  },
  {
    id: 'PC-032',
    title: 'Employment Documentation Case',
    issueType: 'Employment',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2022,
    priority: 'Normal',
    problem: 'Worker required documentation assistance for employee provident fund (PF) queries.',
    actionsTaken: [
      'Checked PF portal details',
      'Verified UAN activation steps'
    ],
    knowledgeUsed: 'PF registry procedures.',
    outcome: 'Resolved',
    resolutionSummary: 'Assisted the client in logging into the portal and updating their profile.',
    documents: ['Employment document'],
    lessonsLearned: 'UAN updates require matching Aadhaar details.',
    tags: ['employment']
  },
  {
    id: 'PC-033',
    title: 'Domestic Violence Support Case',
    issueType: 'Domestic Violence',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Urgent',
    problem: 'Person required coordinated safety support and legal awareness advice.',
    actionsTaken: [
      'Coordinated counseling sessions',
      'Helped write incident logs'
    ],
    knowledgeUsed: 'Domestic violence support guidelines.',
    outcome: 'Support Completed',
    resolutionSummary: 'Assisted in filing safety incidents logs and provided protective shelter.',
    documents: ['Support resource list'],
    lessonsLearned: 'Detailed incident diaries act as strong evidence during reviews.',
    tags: ['domestic-violence']
  },
  {
    id: 'PC-034',
    title: 'Government Scheme Documentation',
    issueType: 'Government Scheme',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Normal',
    problem: 'Applicant needed documentation support for the maternal benefit scheme.',
    actionsTaken: [
      'Verified medical checkup cards',
      'Checked bank account link status'
    ],
    knowledgeUsed: 'Maternal scheme registration checklist.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped client update bank details to receive maternal benefit transfers.',
    documents: ['Identity document', 'Scheme checklist'],
    lessonsLearned: 'Ensure the bank account is Aadhaar seeded for government scheme payments.',
    tags: ['scheme', 'documents']
  },
  {
    id: 'PC-035',
    title: 'Property Documentation Case',
    issueType: 'Land / Property',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Important',
    problem: 'Property documents needed review for partition of family homestead.',
    actionsTaken: [
      'Compiled ancient partition records',
      'Consulted senior expert'
    ],
    knowledgeUsed: 'Homestead partition guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped siblings divide properties through registered mutual agreements.',
    documents: ['Property record'],
    lessonsLearned: 'Registered mutual agreements prevent future boundary disputes.',
    tags: ['property']
  },
  {
    id: 'PC-036',
    title: 'Family Record Support',
    issueType: 'Family',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Normal',
    problem: 'Family records and child immunization data required organization for school admissions.',
    actionsTaken: [
      'Compiled health cards',
      'Drafted admission files'
    ],
    knowledgeUsed: 'School admission documentation guides.',
    outcome: 'Resolved',
    resolutionSummary: 'Organized childhood health logs to secure local primary school admission.',
    documents: ['Identity document'],
    lessonsLearned: 'Keep immunizations cards updated for primary registrations.',
    tags: ['family', 'records']
  },
  {
    id: 'PC-037',
    title: 'Employment Support Case',
    issueType: 'Employment',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Important',
    problem: 'Worker required support understanding employment records after injury.',
    actionsTaken: [
      'Collected medical reports',
      'Reviewed compensation procedures'
    ],
    knowledgeUsed: 'Workplace injury compensation guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped compile medical cards and injury reports for filing.',
    documents: ['Employment document', 'Medical records'],
    lessonsLearned: 'Log injury details within 24 hours of incident.',
    tags: ['employment']
  },
  {
    id: 'PC-038',
    title: 'Land Inheritance Documentation',
    issueType: 'Land / Property',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Important',
    problem: 'Inheritance records required organization for agricultural property partition.',
    actionsTaken: [
      'Collected death certificates',
      'Verified legal heir certificates'
    ],
    knowledgeUsed: 'Legal heir certification rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped client obtain legal heir documents to register properties.',
    documents: ['Property record', 'Family relationship document'],
    lessonsLearned: 'Obtain death certificates within 30 days of demise.',
    tags: ['inheritance', 'land']
  },
  {
    id: 'PC-039',
    title: 'Government Benefit Documentation',
    issueType: 'Government Scheme',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2022,
    priority: 'Normal',
    problem: 'Required documentation for disability pension benefit was unclear.',
    actionsTaken: [
      'Verified medical certificate rules',
      'Checked application form'
    ],
    knowledgeUsed: 'Disability pension scheme rules.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Compiled medical certificates and applied for disability pension.',
    documents: ['Identity document', 'Scheme checklist'],
    lessonsLearned: 'Medical certificates must be signed by authorized doctors.',
    tags: ['government', 'benefit']
  },
  {
    id: 'PC-040',
    title: 'Domestic Support Referral',
    issueType: 'Domestic Violence',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2022,
    priority: 'Urgent',
    problem: 'Person needed access to support resources and legal counseling options.',
    actionsTaken: [
      'Referred to local protection desk',
      'Provided resource list'
    ],
    knowledgeUsed: 'Protection officer liaison procedures.',
    outcome: 'Support Completed',
    resolutionSummary: 'Client was linked with family counseling support.',
    documents: ['Support resource list'],
    lessonsLearned: 'Early counseling prevents escalation of family disputes.',
    tags: ['domestic-violence', 'support']
  },
  {
    id: 'PC-041',
    title: 'Property Boundary Documentation',
    issueType: 'Land / Property',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Important',
    problem: 'Property boundary documentation required review for building partition fence.',
    actionsTaken: [
      'Reviewed boundary survey map',
      'Spoke to neighbors'
    ],
    knowledgeUsed: 'Land survey map validation.',
    outcome: 'Resolved',
    resolutionSummary: 'Boundary coordinates were verified to build fence.',
    documents: ['Property record', 'Boundary document'],
    lessonsLearned: 'Review survey maps before constructing boundary fences.',
    tags: ['property', 'boundary']
  },
  {
    id: 'PC-042',
    title: 'Employment Record Support',
    issueType: 'Employment',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Normal',
    problem: 'Employment records and contract copies required organization for pending claims.',
    actionsTaken: [
      'Organized employment logs',
      'Reviewed contract rules'
    ],
    knowledgeUsed: 'Contract laborer protection rules.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped employee organize work logs to settle contract claims.',
    documents: ['Employment document'],
    lessonsLearned: 'Retain copies of signed work contracts.',
    tags: ['employment', 'records']
  },
  {
    id: 'PC-043',
    title: 'Family Documentation Case',
    issueType: 'Family',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Normal',
    problem: 'Family documentation for marriage registration certificate was incomplete.',
    actionsTaken: [
      'Checked marriage certificate rules',
      'Verified age proofs'
    ],
    knowledgeUsed: 'Marriage registration guidelines.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Assisted in obtaining the marriage registration certificate.',
    documents: ['Family relationship document'],
    lessonsLearned: 'Collect birth certificates of both spouses for registrations.',
    tags: ['family', 'documents']
  },
  {
    id: 'PC-044',
    title: 'Welfare Scheme Support',
    issueType: 'Government Scheme',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Normal',
    problem: 'Applicant needed help understanding documentation for housing scheme.',
    actionsTaken: [
      'Explained income certificate rules',
      'Verified caste certificate details'
    ],
    knowledgeUsed: 'Housing scheme documentation guides.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped compile caste and income certificates for housing scheme.',
    documents: ['Identity document', 'Scheme checklist'],
    lessonsLearned: 'Renew caste and income certificates annually.',
    tags: ['scheme', 'welfare']
  },
  {
    id: 'PC-045',
    title: 'Land Record Support',
    issueType: 'Land / Property',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Important',
    problem: 'Land records and mutation entry RTC documents required clarification.',
    actionsTaken: [
      'Checked mutation registry entries',
      'Verified property titles'
    ],
    knowledgeUsed: 'Property mutation guidelines.',
    outcome: 'Resolved',
    resolutionSummary: 'Assisted client in tracking mutation status at local sub-office.',
    documents: ['Property record'],
    lessonsLearned: 'Verify mutation status within 90 days of registration.',
    tags: ['land', 'records']
  },
  {
    id: 'PC-046',
    title: 'Documentation Assistance Case',
    issueType: 'Documentation',
    district: 'Bengaluru',
    state: 'Karnataka',
    language: 'English',
    year: 2021,
    priority: 'Normal',
    problem: 'Person needed help organizing official documents for credit applications.',
    actionsTaken: [
      'Compiled salary statements',
      'Verified address proofs'
    ],
    knowledgeUsed: 'Address proof validation checklist.',
    outcome: 'Documentation Completed',
    resolutionSummary: 'Organized utility bills and identity proofs to update bank records.',
    documents: ['Identity document'],
    lessonsLearned: 'Utility bills must be under 3 months old to count as address proof.',
    tags: ['documentation']
  },
  {
    id: 'PC-047',
    title: 'Employment Documentation Review',
    issueType: 'Employment',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Important',
    problem: 'Employment records and contract copies required review after salary delay.',
    actionsTaken: [
      'Checked work contracts',
      'Drafted request letter'
    ],
    knowledgeUsed: 'Wage payment dispute procedures.',
    outcome: 'Resolved',
    resolutionSummary: 'Assisted in filing a request to clarify outstanding wage payments.',
    documents: ['Employment document'],
    lessonsLearned: 'Avoid working without a signed copy of the employment contract.',
    tags: ['employment']
  },
  {
    id: 'PC-048',
    title: 'Family Property Support',
    issueType: 'Family',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Normal',
    problem: 'Family required assistance organizing property records and tax receipts.',
    actionsTaken: [
      'Collected tax challan records',
      'Reviewed payment entries'
    ],
    knowledgeUsed: 'Family property tax tracking.',
    outcome: 'Resolved',
    resolutionSummary: 'Compiled and organized 5 years of family property tax receipts.',
    documents: ['Property record'],
    lessonsLearned: 'Keep property tax receipts in chronological order.',
    tags: ['family', 'property']
  },
  {
    id: 'PC-049',
    title: 'Domestic Violence Support Referral',
    issueType: 'Domestic Violence',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Urgent',
    problem: 'Person required safety counseling support and legal protection links.',
    actionsTaken: [
      'Liaised with protection desk',
      'Shared resources folder'
    ],
    knowledgeUsed: 'Counseling referral procedures.',
    outcome: 'Support Completed',
    resolutionSummary: 'Helped link the client with district protection counselor.',
    documents: ['Support resource list'],
    lessonsLearned: 'Direct linkages improve counselor outreach success.',
    tags: ['domestic-violence', 'referral']
  },
  {
    id: 'PC-050',
    title: 'Government Documentation Support',
    issueType: 'Government Scheme',
    district: 'Kolar',
    state: 'Karnataka',
    language: 'Kannada',
    year: 2021,
    priority: 'Normal',
    problem: 'Applicant required help identifying supporting documents for housing subsidy.',
    actionsTaken: [
      'Verified local property deeds',
      'Knowledge checklist search'
    ],
    knowledgeUsed: 'Housing subsidy eligibility guides.',
    outcome: 'Resolved',
    resolutionSummary: 'Helped compile local property deeds to complete the housing application.',
    documents: ['Identity document', 'Scheme checklist'],
    lessonsLearned: 'Ensure deeds are clearly readable before uploading.',
    tags: ['government', 'documentation']
  }
];
